# \u914D\u7F6E Redis \u8FDE\u63A5
#quarkus.redis.hosts=redis://localhost:6379
# \u5982\u679C\u6709 Redis Cluster
#quarkus.redis.hosts=redis://node1:6379,redis://node2:6379
# REDIS_URL=redis://127.0.0.1:6379 ./target/app-runner
# IDE \u6CA1\u8BFB\u53D6\u7CFB\u7EDF\u73AF\u5883\u53D8\u91CF\uFF1A Run Configuration \u2192 Environment Variables \uFF1AREDIS_PWD=ezzBTBzKHwZrMuiGu;REDIS_URL=redis://redis-19.c2.us-east-1-4.ec2.cloud.redislabs.com:19019
quarkus.redis.hosts=${REDIS_URL:redis://localhost:6379}
quarkus.redis.password=${REDIS_PWD:123456}
quarkus.redis.publish-channel-name=${REDIS_PUBLISH_CHANNEL_NAME:router-channel-reactive}
quarkus.redis.subscribe-channel-name=${REDIS_SUBSCRIBE_CHANNEL_NAME:router-channel-reactive}
# quarkus.redis.database=0
# \u8FDE\u63A5\u6C60
quarkus.redis.max-pool-size=20
quarkus.redis.max-pool-waiting=200

# ========= Connector \u5168\u5C40\u914D\u7F6E =========
# MQTT Broker
# 1\uFE0F\u20E3 \u8FDE\u63A5\u7EA7\u522B\u914D\u7F6E\uFF08\u5168\u5C40\uFF09\uFF1A\u5F71\u54CD\u6240\u6709\u4F7F\u7528 smallrye-mqtt \u7684 channel\u3002
mp.messaging.connector.smallrye-mqtt.host=${MQTT_HOST:127.0.0.1}
mp.messaging.connector.smallrye-mqtt.port=${MQTT_PORT:1883}
mp.messaging.connector.smallrye-mqtt.username=${MQTT_NAME:test}
mp.messaging.connector.smallrye-mqtt.password=${MQTT_PWD:12345}
mp.messaging.connector.smallrye-mqtt.client-id=quarkus-mqtt-demo
mp.messaging.connector.smallrye-mqtt.auto-generated-client-id=false

#\u2705 1. \u542F\u7528 TLS
#mp.messaging.connector.smallrye-mqtt.ssl=true
#mp.messaging.connector.smallrye-mqtt.truststore.path=...
#2\uFE0F\u20E3 \u81EA\u52A8\u91CD\u8FDE
mp.messaging.connector.smallrye-mqtt.auto-clean-session=true
mp.messaging.connector.smallrye-mqtt.keep-alive-seconds=30
mp.messaging.connector.smallrye-mqtt.reconnect-interval=5
#mp.messaging.connector.smallrye-mqtt.max-inflight=1024
mp.messaging.connector.smallrye-mqtt.max-inflight=2048
# \u8BBE\u7F6E clean-session: \u907F\u514D\u91CD\u542F\u4E22\u5931 QoS1/2 \u6D88\u606F\u3002
mp.messaging.connector.smallrye-mqtt.clean-session=false

# 2\uFE0F\u20E3 Channel \u7EA7\u522B\u914D\u7F6E\uFF1A \u5F71\u54CD\u6240\u6709\u4F7F\u7528 smallrye-mqtt \u7684 channel\u3010mp.messaging.incoming.<channel-name>.connector=smallrye-mqtt\u3011
# \u7ED3\u6784\u89C4\u5219\uFF1Amp.messaging.<\u65B9\u5411>.<channel-name>.<\u5C5E\u6027>
# | \u90E8\u5206          | \u8BF4\u660E                 |
# | ----------- | ------------------ |
# | incoming    | \u8BA2\u9605                 |
# | outgoing    | \u53D1\u5E03                 |
# | temperature | channel \u540D\uFF08\u5FC5\u987B\u548C\u4EE3\u7801\u4E00\u81F4\uFF09 |
# | connector   | \u4F7F\u7528\u54EA\u4E2A connector     |
# | topic       | \u8BA2\u9605/\u53D1\u5E03\u7684 MQTT topic  |
# ============ INCOMING ============
mp.messaging.incoming.temperature.connector=smallrye-mqtt
# 1\uFE0F\u20E3 \u5355\u4E2A Topic\uFF08\u6700\u7B80\u5355\uFF09\u548C outgoing\u547D\u540D\u4E00\u6837\uFF1A\u7528\u4E8E\u5355\u4E00\u529F\u80FD\u7684\u6D88\u8D39\u8005\uFF1B\u9002\u5408 IoT \u8BBE\u5907\u5355\u4E00\u6570\u636E\u6D41\uFF1B\u53EF\u9760\u6027\u53EF\u901A\u8FC7 ack-strategy=manual \u548C QoS1/2 \u4FDD\u8BC1
#mp.messaging.incoming.temperature.topic=sensor/temperature
# 2\uFE0F\u20E3 \u591A Topic \u8BA2\u9605\uFF08\u901A\u914D\u7B26\uFF09
# + \u5339\u914D\u5355\u7EA7 Topic \uFF1A sensor/+ \u2192  \u3010sensor/temperature, sensor/humidity\u3011
# # \u5339\u914D\u591A\u7EA7 Topic \uFF1A sensor/# \u2192   \u3010sensor/temperature, sensor/alert/device1\u3011
mp.messaging.incoming.temperature.topic=sensor/+
# \u914D\u7F6E\u65B9\u5F0F\uFF1Amp.messaging.incoming.temperature.qos>=1 \u548C mp.messaging.outgoing.alert.qos>=1\u624D\u652F\u6301ack
#| QoS | \u8BF4\u660E           |
#| --- | ------------ |
#| 0   | \u81F3\u591A\u4E00\u6B21\uFF08\u65E0 ACK\uFF09  |
#| 1   | \u81F3\u5C11\u4E00\u6B21\uFF08PUBACK\uFF09 |
#| 2   | \u6070\u597D\u4E00\u6B21\uFF08\u56DB\u6B65\u63E1\u624B\uFF09   |
mp.messaging.incoming.temperature.qos=1
# ACK \u7B56\u7565\u914D\u7F6E
# | \u7B56\u7565              | \u8BF4\u660E          |
# | --------------- | ----------- |
# | post-processing | \u9ED8\u8BA4          |
# | pre-processing  | \u6536\u5230\u5373\u786E\u8BA4       |
# | manual          | \u4F60\u5FC5\u987B\u8C03\u7528 ack() |
mp.messaging.incoming.temperature.ack-strategy=manual
# NACK \u5982\u4F55\u5904\u7406\uFF1F\u4F60\u53EF\u4EE5\u8BBE\u7F6E failure-strategy\uFF1A
# | \u7B56\u7565                | \u4F5C\u7528      |
# | ----------------- | ------- |
# | fail              | \u5E94\u7528\u5D29\u6E83    |
# | ignore            | \u5FFD\u7565\u9519\u8BEF    |
# | dead-letter-queue | \u53D1\u9001\u5230 DLQ |
mp.messaging.incoming.temperature.failure-strategy=fail
#\u771F\u6B63\u7684\u201C\u9AD8\u53EF\u9760\u201D\u914D\u7F6E\u7EC4\u5408\uFF08\u63A8\u8350\uFF09
#MQTT \u81F3\u5C11\u4E00\u6B21\u4FDD\u8BC1
#\u4E1A\u52A1\u5904\u7406\u6210\u529F\u624D ACK
#\u5D29\u6E83\u4E0D\u4F1A\u4E22\u672A\u786E\u8BA4\u6D88\u606F
#\u91CD\u542F\u53EF\u6062\u590D\u672A\u786E\u8BA4\u6D88\u606F
#mp.messaging.incoming.temperature.qos=1
#mp.messaging.incoming.temperature.ack-strategy=manual
#mp.messaging.incoming.temperature.failure-strategy=fail
#mp.messaging.connector.smallrye-mqtt.clean-session=false

# ============ OUTGOING ============
mp.messaging.outgoing.alert.connector=smallrye-mqtt
mp.messaging.outgoing.alert.topic=sensor/alert
mp.messaging.outgoing.alert.qos=1
mp.messaging.outgoing.alert.retain=true
mp.messaging.outgoing.alert.auto-generated-client-id=false

# Your configuration properties
# quarkus.rest-client."com.ewancle.service.RestClientService".url=https://stage.code.quarkus.io/api
# Your configuration properties
quarkus.rest-client.remote-api.url=https://stage.code.quarkus.io/api
quarkus.rest-client.remote-api.scope=jakarta.inject.Singleton
quarkus.rest-client.remote-api.connect-timeout=5000
quarkus.rest-client.remote-api.read-timeout=10000
quarkus.rest-client.remote-api.connection-pool-size=50
quarkus.rest-client.remote-api.max-redirects=5
# \u542F\u7528 HTTP/2
quarkus.rest-client.remote-api.http2=true
quarkus.rest-client.remote-api.alpn=true
#\u65B9\u5F0F 1\uFF1A\u4F7F\u7528 truststore
#quarkus.tls.trust-all=true
#quarkus.rest-client.remote-api.trust-store=classpath:truststore.jks
#quarkus.rest-client.remote-api.trust-store-password=changeit
# \u5FFD\u7565\u8BC1\u4E66
quarkus.tls.tls-disabled.trust-all=true
quarkus.tls.tls-disabled.hostname-verification-algorithm=NONE
quarkus.rest-client.remote-api.tls-configuration-name=tls-disabled
# \u538B\u7F29\u652F\u6301
#quarkus.rest-client.enable-compression=true
#quarkus.rest-client.remote-api.enable-compression=true
# \u4EE3\u7406
quarkus.proxy.my-proxy.host=localhost
quarkus.proxy.my-proxy.port=8183
quarkus.proxy.my-proxy.username=username
quarkus.proxy.my-proxy.password=password
quarkus.proxy.my-proxy.non-proxy-hosts=my.company.com
quarkus.rest-client.client1.proxy-configuration-name=my-proxy

#quarkus.http.body.uploads-directory=/tmp/uploads
#quarkus.http.limits.max-form-attribute-size=10M
#quarkus.http.limits.max-body-size=100M
