name: Deploy

on:
  workflow_run:
    workflows: ["openwrt-cross-platform-build"]
    types:
      - completed
jobs:
  deploy:
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    if: |
      (github.event_name == 'push' && contains(github.event.head_commit.message, 'deploy prod')) ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'deploy prod')) ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && startsWith(github.ref, 'refs/tags/'))
    runs-on: ubuntu-latest

    steps:
      - name: deploy
        run: echo "deploy project"