name: Deploy

permissions:
  contents: write
  discussions: write

on:
  workflow_run:
    workflows: ["openwrt-cross-platform-build"]
    types: # types 用来指定 workflow_run 事件的类型，目前官方支持 ： completed 当 workflow 完成执行时触发（无论成功、失败、取消）； requested 当 workflow 被请求启动时触发（一般很少用）
      - completed
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # workflow_run.conclusion 可能的值：
    # | 值           | 含义                       |
    #| ----------- | ------------------------ |
    #| `success`   | workflow 成功完成            |
    #| `failure`   | workflow 执行失败            |
    #| `cancelled` | workflow 被取消             |
    #| `skipped`   | workflow 被跳过             |
    #| `neutral`   | workflow 中性状态（未被视为成功或失败） |
    #if: |
    #  (github.event_name == 'push' && contains(github.event.head_commit.message, 'deploy prod')) ||
    #  (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'deploy prod')) ||
    #  (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && startsWith(github.ref, 'refs/tags/'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact-merged-ids-${{ github.event.repository.name }}
          repository: ${{ github.repository }}
          path: /tmp
          # 从其他工作流运行甚至其他存储库下载工件可能很有用。默认情况下，权限范围有限，只能下载当前工作流运行中的工件。
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # 默认 ${{ github.run_id }} 当前工作流运行id，跨工作流需要指定运行id
          run-id: ${{ github.event.workflow_run.id }}
      - name: Load variables
        id: ver
        run: |
          source /tmp/artifact-merged-ids.txt
          echo "前一个运行文件的环境变量=$UPLOAD_ARTIFACT_IDS"
          echo "ids=$UPLOAD_ARTIFACT_IDS" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v6
      # 3. 下载所有 Artifacts
      - name: Download All Artifacts
        uses: actions/download-artifact@v5
        with:
          path: ./artifact
          #pattern: artifact-${{ github.event.repository.name }}-*
          #artifact-ids: 12345,67890
          artifact-ids: ${{ steps.ver.outputs.ids }}
          merge-multiple: true
          # 从其他工作流运行甚至其他存储库下载工件可能很有用。默认情况下，权限范围有限，只能下载当前工作流运行中的工件。
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # 默认 ${{ github.run_id }} 当前工作流运行id，跨工作流需要指定运行id
          run-id: ${{ github.event.workflow_run.id }}
      - name: List Downloaded Files
        run: ls -lRh ./artifact
      - name: Generate Changelog
        run: echo "# 加载文本的路径，该文本说明了此版本中的重大变更" > ${{ github.workspace }}-CHANGELOG.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        #if: github.ref_type == 'tag' || startsWith(github.ref, 'refs/tags/')
        if: startsWith(github.ref, 'refs/tags/')
        with:
          # name: 发布版本名称。默认为标签名称。
          # tag_name: 标签名称。默认为github.ref_name
          token: ${{ secrets.GITHUB_TOKEN }}
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          # 此版本中的重要变更说明文本，和body_path同时存在，优先body
          # body: "重要变更说明文本"
          # 指示此版本是否为草稿的指标
          draft: false
          # 指示是否为预发布版本的指标
          prerelease: false
          # 指示上传资源时是否应保留文件顺序
          preserve_order: true
          # 以换行符分隔的待发布资源路径字符串
          files: |
            ./artifact/*
          # 指示如果任何通配符files不匹配则是否失败
          #fail_on_unmatched_files: false
          # 如果指定，则会创建指定类别的讨论并将其链接到该版本。该值必须是存储库中已存在的类别。
          #discussion_category_name: 创建类别:https://docs.github.com/en/discussions/managing-discussions-for-your-community/managing-categories-for-discussions
          # 是否自动生成此版本的名称和正文。如果指定了名称，则使用指定的名称；否则，将自动生成名称。如果指定了正文，则正文内容将添加到自动生成的说明之前。https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
          #generate_release_notes: true
          # 追加到现有正文中，而不是覆盖它。
          #append_body: true
          # 指定是否应将此版本设置为仓库的最新版本。草稿和预发布版本不能设置为最新版本。可设值：true, false, or legacy
          # make_latest: true
